CC = g++

OPENGLLIB = -lGL
GLEWLIB = -lGLEW
GLFWLIB = -lglfw
LIBS = $(OPENGLLIB) $(GLEWLIB) $(GLFWLIB)
LDFLAGS = -L/usr/local/lib 
CPPFLAGS =-I/usr/local/include

BIN = assign1
SRCS = main.cpp gl_framework.cpp shader_util.cpp 
INCLUDES = gl_framework.hpp shader_util.hpp

all: $(BIN)

$(BIN): $(SRCS) $(INCLUDES)
	g++ $(CPPFLAGS) $(SRCS) -o $(BIN) $(LDFLAGS) $(LIBS)

clean:
	rm -f *~ *.o $(BIN)